# .readthedocs.yaml

# Required
version: 0.1

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    # You can also specify other tool versions:
    # nodejs: "19"
    # rust: "1.64"
    # golang: "1.19"

mkdocs:
  configuration: mkdocs.yml